development:
  adapter: redis

test:
  adapter: test

production:
  adapter: redis
  url: redis://redistogo:ead83621ff28f051d720bda52af7e87a@barb.redistogo.com:10250/
  # channel_prefix: teamwork_backend_production
